app/models/Word.py
from app import db
from .BaseMixin import BaseMixin

class Word(BaseMixin, db.Model):

    word = db.Column(db.String(60), unique=True)

    texts = db.relationship('Text', backref='word_text', lazy='dynamic')

    def __repr__(self):
        return '<Word: {}>'.format(self.word)

app/word/forms.py
# app/word/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField,TextAreaField, SelectField, \
    HiddenField, validators, SelectMultipleField, IntegerField

from wtforms.widgets import ListWidget,CheckboxInput

from wtforms.validators import DataRequired
from ..models.Language import Language

class SearchWordForm(FlaskForm):
    word = StringField('Word', validators=[DataRequired()])

class WordForm(FlaskForm):

    word_id = HiddenField("WordId")

    word = StringField('Word', [validators.required(), validators.length(max=60)])
    definition = TextAreaField('Definition', [validators.required(), validators.length(max=200)])
    example = TextAreaField('Example', [validators.required(), validators.length(max=200)])
    tags = TextAreaField('Tags', [validators.required(), validators.length(max=200)])
    language = SelectField(u'Language', choices=[], coerce=int)

    submit = SubmitField('Submit')

class MultiCheckboxField(SelectMultipleField):
    """
    A multiple-select, except displays a list of checkboxes.

    Iterating the field will produce subfields, allowing custom rendering of
    the enclosed checkbox fields.
    """
    widget = ListWidget(prefix_label=False)
    option_widget = CheckboxInput()

class RelatedWordForm(FlaskForm):

    word = HiddenField("Word")
    words = MultiCheckboxField(coerce=int)

    submit = SubmitField('Submit')

app/word/__init__.py
# app/word/__init__.py

from flask import Blueprint

word_blueprint = Blueprint('word', __name__)

from . import views

app/word/views.py
# app/word/views.py

from flask import abort, flash, redirect, render_template, url_for, g
from flask_login import login_required, current_user

from sqlalchemy.sql import func
from sqlalchemy import tuple_
from sqlalchemy.orm import aliased

from . import word_blueprint
from ..models.Word import Word
from ..models.Text import Text
from ..models.Rating import Rating
from ..models.Language import Language
from ..models.Relation import Relation
from ..models.Tag import Tag
from ..models.TagText import TagText

from .. import db
from .forms import WordForm, RelatedWordForm


@word_blueprint.errorhandler(404)
def page_not_found(e):
    return render_template('word/404.html'), 404


@word_blueprint.route('/<string:term>', defaults={ "text_id":None, "action":None})
@word_blueprint.route('/<string:term>/<int:text_id>', defaults={ "action":None})
@word_blueprint.route('/<string:term>/<int:text_id>/<string:action>')
def word(term, text_id=None, action=None):

    if action != None and text_id != None:
        DefineRating(term,text_id,action)

    word = Word.query \
        .filter(Word.word.ilike(term)) \
        .first_or_404()

    if text_id != None:
        texts = word.texts.filter(Text.id==text_id)
        onlyText=True

        if texts.count() == 0:
            abort(404)
    else:
        texts = word.texts.order_by(Text.num_ratings.desc())
        onlyText=False

    if word is None:
        abort(404)

    return render_template('word/word.html',
                           word=word,
                           texts=texts,
                           onlyText=onlyText,
                           title="Word")


@word_blueprint.route('/add', defaults={ "term":None }, methods=['GET',"POST"])
@word_blueprint.route('/add/<string:term>', methods=['GET', 'POST'])
@login_required
def add_word(term):

    form = WordForm()
    form.language.choices=[(g.id, g.name) for g in Language.query.order_by('name')]

    word = None
    if term != None:
        word = Word.query.filter(Word.word==term).first_or_404()
        form.word.data = word.word
        form.word(disabled=True)
        form.word_id.data = word.id

    if form.validate_on_submit():


        if form.word_id.data != "":
            word = Word.query.filter(Word.id==form.word_id.data).first_or_404()
        else:
            word = Word(word=form.word.data, created_by_id=current_user.id)

        textDescription = Text(text=form.definition.data,
                               type=1,
                               language_id=form.language.data,
                               created_by_id=current_user.id)

        for tagText in form.tags.data.split(" "):
            tag = Tag.query.filter(Tag.tag.ilike(tagText)).first()

            if tag is None:
                tag = Tag(tag=tagText, created_by_id=current_user.id, language_id=form.language.data)

            textDescription.tags.append(tag)

        textExample = Text(text=form.example.data,
                           type=2,
                           language_id=form.language.data,
                           created_by_id=current_user.id)

        textDescription.sons.append(textExample)

        word.texts.append(textDescription)
        word.texts.append(textExample)

        try:
            db.session.add(word)

            db.session.commit()
            flash("Word added!")

            return redirect(url_for("word.word", term=word.word))

        except:
            flash("Error")

    return render_template('word/addword.html',
                           form=form,
                           word=word,
                           add_word=True)


@word_blueprint.route('/addrelatedword/<string:word>/<int:text_id>', methods=['GET', "POST"])
@login_required
def add_related_word(word,text_id):

    form = RelatedWordForm()

    word = Word.query.filter(Word.word==word).first_or_404()

    nottexts = db.session.query(Text, Relation) \
        .join(Relation, Text.id == Relation.text_id_to)\
        .filter(Text.id==text_id) \
        .with_entities(Relation.text_id_from)

    notwords = db.session.query(Text) \
        .filter(Text.id.in_(nottexts)) \
        .with_entities(Text.word_id)

    form.word.data = word.word
    words = db.session.query(Word, Text) \
        .join(Text, Text.word_id == Word.id) \
        .filter(Text.type != 2) \
        .filter(Text.id != text_id) \
        .filter(Word.id != word.id) \
        .filter(Word.id.notin_(notwords)) \
        .order_by(Word.word) \
        .with_entities(Text.id, (Word.word + ": " + Text.text).label("text"))

    if words.count() == 0:
        flash("No words availables to relate")
        return redirect(url_for("word.word", term=word.word))

    form.words.choices = [(g.id, g.text) for g in words]

    if form.validate_on_submit():

        try:
            for text_form in form.words.data:
                db.session.add(Relation(text_id_to=text_id, text_id_from=text_form))
                db.session.add(Relation(text_id_to=text_form, text_id_from=text_id))

            db.session.commit()
            flash("Relation added!")

        except:
            flash("Error")

        return redirect(url_for("word.word", term=form.word.data))

    return render_template('word/addrelatedword.html',
                           form=form,
                           word=word)


@word_blueprint.route('/delete/<string:word>', methods=['GET'])
@login_required
def delete_word(word):
    word = Word.query.filter(Word.word == word).first_or_404()

    if word.created_by_id != current_user.id:
        abort(401)

    db.session.delete(word)
    db.session.commit()
    flash('You have successfully deleted the word.')

    # redirect to the roles page
    return redirect(url_for('dictionary.index'))


def DefineRating(term, text_id, action):

    if action == "like":
        ratingType = 1
    else:
        ratingType = -1

    execute = True

    exist = Rating.query.filter(Rating.text_id==text_id, Rating.created_by_id==current_user.id)
    if exist.count() != 0:

        if exist.first().rating != ratingType:
            db.session.delete(exist.first())
            db.session.commit()
        else:
            execute = False
            flash("You already {0} this word".format(action))

    if execute:

        rating = Rating(text_id=text_id, rating=ratingType, created_by_id=current_user.id)

        try:
            db.session.add(rating)
            db.session.commit()
            flash("{0} added to text".format(action))
        except:
            flash("Error")

app/templates/word/_word.html
<li class="words">

    <div class="row header-word">
        <div class="col-md-10">
            <h2><a href="{{ url_for('word.word', term=word.word) }}">{{ word.word }}</a></h2>
        </div>
        <div class="col-md-2 ">
            <div class="addthis_inline_share_toolbox"
                addthis:description="{{ word.texts.first().text }}">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-10">
            <h3>Definitions</h3>
        </div>
        <div class="col-md-2 ">
            <div class="add_definition">
                <a href="{{ url_for("word.add_word", term=word.word) }}">
                    Add Definition
                </a>
            </div>
        </div>
    </div>

    <ol class="definitions">

        {% for text in texts|rejectattr('type', "equalto", 2)|list %}

            <li>
                <div class="row row-word" style="border-right: 15px solid #{{ text.language.color }}">
                    <div class="col-md-1">
                        <ul class="rating">
                            <li><a href="{{ url_for("word.word", term=word.word, text_id=text.id, action="like") }}"><span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span></a></li>
                            <li>{{ text.ratings|sum(attribute='rating') }}</li>
                            <li><a href="{{ url_for("word.word", term=word.word, text_id=text.id, action="dislike") }}"><span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span></a></li>
                        </ul>
                    </div>

                    <div class="col-md-11">
                        <p class="text_word">{{ text.text }}</p>

                        {% if text.sons != None %}
                            <ol class="examples">
                                {% for example in text.sons %}
                                    <li><i>{{ example.text }}</i></li>
                                {% endfor %}
                            </ol>
                        {% endif %}

                        <div class="more">
                            <span>by {{ text.lexicographer.username }}, {{ text.timestamp.strftime('%d-%m-%Y') }}</span>

                            <span><a href="{{ url_for("dictionary.language", language=text.language.name) }}">#{{ text.language.name }}</a></span>

                            {% for tag in text.tags %}
                                <span><a href="{{ url_for("dictionary.tag", tag=tag.tag) }}">#{{ tag.tag }}</a></span>
                            {% endfor %}


                        </div>
                    </div>

                </div>

                {% if text.relations != None %}
                    <ul class="related-words">
                        <li>Related words:</li>
                        {% for relation in text.relations %}
                            <li style="border-right: 10px solid #{{ relation.relations_from.language.color }};">
                                <a href="{{ url_for("word.word", term=relation.relations_from.word.word) }}">
                                    {{ relation.relations_from.word.word }}
                                </a>
                            </li>
                        {% endfor %}
                        <li>
                            <a href="{{ url_for("word.add_related_word", word=word.word, text_id=text.id) }}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                            </a>
                        </li>
                    </ul>
                {% endif %}

            </li>

        {% endfor %}



    </ol>

    {% if word.created_by_id == current_user.id %}
        <p><a href="{{ url_for('word.delete_word', word=word.word) }}">Delete</a></p>
    {% endif %}
</li>

app/templates/word/addrelatedword.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    | Add related word
{% endblock %}

{% block metatags %}

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="Description" CONTENT="Let's go fella, write that shit down">
    <meta name="robots" content="index,follow">

{% endblock %}

{% block body %}
    <div class="container">

        <h1>Add related word to <i>{{ word.word }}</i></h1>
        <br/>

        <form method="POST" class="formrelatedwords" >
            {{ form.hidden_tag() }}
            <div>{{ form.words.label }}: {{ form.words(class="css_class") }}</div>

            <p>&nbsp;</p>
            <div class="btn-toolbar" role="group" aria-label="Actions">
                <div class="btn-group" role="group" aria-label="...">{{ form.submit(class="btn btn-primary") }}</div>
                <div class="btn-group" role="group" aria-label="...">
                    <a href="{{ url_for("word.word", term=word.word) }}">Return to {{ word.word }}</a></div>
            </div>
        </form>

        {% for field in form if field.widget.input_type != 'hidden' %}
            {% if field.errors %}
                <span style="color: red;">{% for error in field.errors %}{{ error }}{% if not loop.last %}<br />{% endif %}{% endfor %}</span>
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

app/templates/word/addword.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    | Add word
{% endblock %}

{% block metatags %}

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="Description" CONTENT="Let's go fella, write that shit down">
    <meta name="robots" content="index,follow">

{% endblock %}

{% block body %}
    <div class="container">

        <h1>
            {% if add_word == True %}
                {% if word == None %}
                    Add Word
                {% else %}
                    Add Definition
                {% endif %}
            {% else %}
                Edit Word
            {% endif %}
        </h1>
        <br/>
        {{ wtf.quick_form(form) }}
    </div>

{% endblock %}

app/templates/word/word.html
<!-- app/templates/home/index.html -->
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}
    | {{ word.word }}
{% endblock %}

{% block metatags %}

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="Description" CONTENT="{{ word.texts.first().text }}">
    <meta name="robots" content="index,follow">

    <meta property="og:title" content="Dialleto | {{ word.word }}" />
    <meta property="og:description" content="{{ word.texts.first().text }}. See more definitions" />

{% endblock %}
{% block body %}


    <div class="container">
        <br>
        {{ utils.flashed_messages() }}
        <ul class="word">
            {% include '/word/_word.html' %}
        </ul>

        {% if onlyText %}
            <a href="{{ url_for("word.word", term=word.word) }}">See all definitions</a>
        {% endif %}
    </div>

{% endblock %}