app/models/Language.py
from app import db
from .BaseMixin import BaseMixin

class Language(BaseMixin, db.Model):

    name = db.Column(db.String(60), unique=True, nullable=False)
    code = db.Column(db.String(6), unique=True, nullable=False)

    color = db.Column(db.String(7))

    parent_id = db.column(db.Integer, db.ForeignKey('languages.id'))

    texts = db.relationship('Text', backref='language_texts', lazy='dynamic')
    tags  = db.relationship('Tag', backref='language_tag', lazy='dynamic')
    #sons = db.relationship('Language', backref='language_sons', lazy='dynamic')

    #sons = db.relationship('Language',
    #                       backref=db.backref('language_sons', remote_side='Language.id'),
     #                      viewonly=True,
    #                       lazy='dynamic')
    def __repr__(self):
        return '<Language: {}>'.format(self.name)

app/models/Tag.py
from app import db
from .BaseMixin import BaseMixin

class Tag(BaseMixin, db.Model):

    tag = db.Column(db.String(30), unique=True, nullable=False)

    language_id = db.Column(db.Integer, db.ForeignKey('languages.id'))

    language = db.relationship('Language', back_populates='tags')

    texts = db.relationship(
        "Text",
        secondary="tag_text",
        back_populates="tags")

    def __repr__(self):
        return '<Tag: {}>'.format(self.text)

app/models/Word.py
from app import db
from .BaseMixin import BaseMixin

class Word(BaseMixin, db.Model):

    word = db.Column(db.String(60), unique=True)

    texts = db.relationship('Text', backref='word_text', lazy='dynamic')

    def __repr__(self):
        return '<Word: {}>'.format(self.word)

app/word/forms.py
# app/word/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField,TextAreaField, SelectField, \
    HiddenField, validators, SelectMultipleField, IntegerField

from wtforms.widgets import ListWidget,CheckboxInput

from wtforms.validators import DataRequired
from ..models.Language import Language

class SearchWordForm(FlaskForm):
    word = StringField('Word', validators=[DataRequired()])

class WordForm(FlaskForm):

    word_id = HiddenField("WordId")

    word = StringField('Word', [validators.required(), validators.length(max=60)])
    definition = TextAreaField('Definition', [validators.required(), validators.length(max=200)])
    example = TextAreaField('Example', [validators.required(), validators.length(max=200)])
    tags = TextAreaField('Tags', [validators.required(), validators.length(max=200)])
    language = SelectField(u'Language', choices=[], coerce=int)

    submit = SubmitField('Submit')

class MultiCheckboxField(SelectMultipleField):
    """
    A multiple-select, except displays a list of checkboxes.

    Iterating the field will produce subfields, allowing custom rendering of
    the enclosed checkbox fields.
    """
    widget = ListWidget(prefix_label=False)
    option_widget = CheckboxInput()

class RelatedWordForm(FlaskForm):

    word = HiddenField("Word")
    words = MultiCheckboxField(coerce=int)

    submit = SubmitField('Submit')

app/dictionary/__init__.py
# app/dictionary/__init__.py

from flask import Blueprint

dic_blueprint = Blueprint('dictionary', __name__)

from . import views

app/dictionary/views.py
# app/word/views.py

from flask import abort, flash, redirect, render_template, url_for, g
from flask_login import login_required, current_user

from sqlalchemy.sql import func

from . import dic_blueprint
from ..models.Word import Word
from ..models.Text import Text
from ..models.Language import Language
from ..models.Tag import Tag
from ..models.TagText import TagText
from ..models.Lexicographer import Lexicographer

from .. import db



@dic_blueprint.route('/')
def index():

    words = get_words(None, 2)

    languages = Language.query.all()
    tags = Tag.query.all()

    return render_template('dictionary/index.html',
                           words=words,
                           languages=languages,
                           tags=tags,
                           title="Dialleto")


@dic_blueprint.route('/search', methods=['POST'])
@dic_blueprint.route('/search/<int:page>', defaults={ "term":"" }, methods=['GET',"POST"])
@dic_blueprint.route('/search/<int:page>/<string:term>', methods=['GET', "POST"])
def search(page=1, term=None):

    if term == None:
        #if not g.search_form.validate_on_submit():
        #else:
        term = g.search_form.word.data

    if term == None:
        return redirect(url_for('index'))

    words = get_words(term)

    if words.count() == 1:
        return redirect(url_for("word.word", term=words.first().word))

    pagination = words.paginate(page, 2, False)

    return render_template('dictionary/search.html',
                           words=pagination.items,
                           pagination=pagination,
                           term=term,
                           title="Dialleto")


@dic_blueprint.route('/random')
def random():
    words = get_words(None)
    return redirect(url_for("word.word", term=words.one().word))


@dic_blueprint.route('/tag/<string:tag>')
def tag(tag):
    words = query_word().filter(Tag.tag == tag)
    tag=Tag.query.filter(Tag.tag==tag).first_or_404()

    return render_template('dictionary/tag.html',
                           tag=tag.tag,
                           words=words,
                           title="Dialleto")

@dic_blueprint.route('/language/<string:language>')
def language(language):
    words = query_word().filter(Language.name == language)
    language = Language.query.filter(Language.name==language).first_or_404()

    return render_template('dictionary/language.html',
                           language=language,
                           words=words,
                           title="Dialleto")


def query_word():
    words = db.session.query(Word, Text, Language, TagText, Tag) \
        .join(Text, Text.word_id == Word.id) \
        .join(Language, Language.id == Text.language_id) \
        .join(TagText, Text.id == TagText.text_id) \
        .join(Tag, Tag.id == TagText.tag_id) \
        .order_by(Text.timestamp.desc()) \
        .with_entities(Word.id, Word.word, Text.timestamp, Text.text, Language.name, Language.code, Word.created_by_id)

    return words

def get_words(term, quantity=1):
    # if we haven`t received a term to search, randomize the words

    PopularDescription = Text
    popular_description_id = db.session.query(PopularDescription.id)\
                    .filter(PopularDescription.word_id == Word.id)\
                    .limit(1)\
                    .correlate(Word)\
                    .as_scalar()

    get_words = db.session.query(Word, Text, Language, Lexicographer)\
        .join(Text, Text.id == popular_description_id)\
        .join(Language, Language.id == Text.language_id)\
        .join(Lexicographer, Lexicographer.id == Text.created_by_id)\
        .with_entities(Word.id, Word.word, Text.timestamp, Text.text, Text.id.label("text_id"),  \
                       Language.name, Language.code, Word.created_by_id, Lexicographer.username, \
                       Text.num_ratings, Language.color)

    if term is None:

        return get_words.offset(
            func.floor(
                func.random() *
                db.session.query(func.count(Word.id))
            )
            ).limit(quantity)

    # otherwise use our term to search
    else:
        return get_words.filter(Word.word.ilike("%" + term + "%"))

app/word/__init__.py
# app/word/__init__.py

from flask import Blueprint

word_blueprint = Blueprint('word', __name__)

from . import views

app/word/views.py
# app/word/views.py

from flask import abort, flash, redirect, render_template, url_for, g
from flask_login import login_required, current_user

from sqlalchemy.sql import func
from sqlalchemy import tuple_
from sqlalchemy.orm import aliased

from . import word_blueprint
from ..models.Word import Word
from ..models.Text import Text
from ..models.Rating import Rating
from ..models.Language import Language
from ..models.Relation import Relation
from ..models.Tag import Tag
from ..models.TagText import TagText

from .. import db
from .forms import WordForm, RelatedWordForm


@word_blueprint.errorhandler(404)
def page_not_found(e):
    return render_template('word/404.html'), 404


@word_blueprint.route('/<string:term>', defaults={ "text_id":None, "action":None})
@word_blueprint.route('/<string:term>/<int:text_id>', defaults={ "action":None})
@word_blueprint.route('/<string:term>/<int:text_id>/<string:action>')
def word(term, text_id=None, action=None):

    if action != None and text_id != None:
        DefineRating(term,text_id,action)

    word = Word.query \
        .filter(Word.word.ilike(term)) \
        .first_or_404()

    if text_id != None:
        texts = word.texts.filter(Text.id==text_id)
        onlyText=True

        if texts.count() == 0:
            abort(404)
    else:
        texts = word.texts.order_by(Text.num_ratings.desc())
        onlyText=False

    if word is None:
        abort(404)

    return render_template('word/word.html',
                           word=word,
                           texts=texts,
                           onlyText=onlyText,
                           title="Word")


@word_blueprint.route('/add', defaults={ "term":None }, methods=['GET',"POST"])
@word_blueprint.route('/add/<string:term>', methods=['GET', 'POST'])
@login_required
def add_word(term):

    form = WordForm()
    form.language.choices=[(g.id, g.name) for g in Language.query.order_by('name')]

    word = None
    if term != None:
        word = Word.query.filter(Word.word==term).first_or_404()
        form.word.data = word.word
        form.word(disabled=True)
        form.word_id.data = word.id

    if form.validate_on_submit():


        if form.word_id.data != "":
            word = Word.query.filter(Word.id==form.word_id.data).first_or_404()
        else:
            word = Word(word=form.word.data, created_by_id=current_user.id)

        textDescription = Text(text=form.definition.data,
                               type=1,
                               language_id=form.language.data,
                               created_by_id=current_user.id)

        for tagText in form.tags.data.split(" "):
            tag = Tag.query.filter(Tag.tag.ilike(tagText)).first()

            if tag is None:
                tag = Tag(tag=tagText, created_by_id=current_user.id, language_id=form.language.data)

            textDescription.tags.append(tag)

        textExample = Text(text=form.example.data,
                           type=2,
                           language_id=form.language.data,
                           created_by_id=current_user.id)

        textDescription.sons.append(textExample)

        word.texts.append(textDescription)
        word.texts.append(textExample)

        try:
            db.session.add(word)

            db.session.commit()
            flash("Word added!")

            return redirect(url_for("word.word", term=word.word))

        except:
            flash("Error")

    return render_template('word/addword.html',
                           form=form,
                           word=word,
                           add_word=True)


@word_blueprint.route('/addrelatedword/<string:word>/<int:text_id>', methods=['GET', "POST"])
@login_required
def add_related_word(word,text_id):

    form = RelatedWordForm()

    word = Word.query.filter(Word.word==word).first_or_404()

    nottexts = db.session.query(Text, Relation) \
        .join(Relation, Text.id == Relation.text_id_to)\
        .filter(Text.id==text_id) \
        .with_entities(Relation.text_id_from)

    notwords = db.session.query(Text) \
        .filter(Text.id.in_(nottexts)) \
        .with_entities(Text.word_id)

    form.word.data = word.word
    words = db.session.query(Word, Text) \
        .join(Text, Text.word_id == Word.id) \
        .filter(Text.type != 2) \
        .filter(Text.id != text_id) \
        .filter(Word.id != word.id) \
        .filter(Word.id.notin_(notwords)) \
        .order_by(Word.word) \
        .with_entities(Text.id, (Word.word + ": " + Text.text).label("text"))

    if words.count() == 0:
        flash("No words availables to relate")
        return redirect(url_for("word.word", term=word.word))

    form.words.choices = [(g.id, g.text) for g in words]

    if form.validate_on_submit():

        try:
            for text_form in form.words.data:
                db.session.add(Relation(text_id_to=text_id, text_id_from=text_form))
                db.session.add(Relation(text_id_to=text_form, text_id_from=text_id))

            db.session.commit()
            flash("Relation added!")

        except:
            flash("Error")

        return redirect(url_for("word.word", term=form.word.data))

    return render_template('word/addrelatedword.html',
                           form=form,
                           word=word)


@word_blueprint.route('/delete/<string:word>', methods=['GET'])
@login_required
def delete_word(word):
    word = Word.query.filter(Word.word == word).first_or_404()

    if word.created_by_id != current_user.id:
        abort(401)

    db.session.delete(word)
    db.session.commit()
    flash('You have successfully deleted the word.')

    # redirect to the roles page
    return redirect(url_for('dictionary.index'))


def DefineRating(term, text_id, action):

    if action == "like":
        ratingType = 1
    else:
        ratingType = -1

    execute = True

    exist = Rating.query.filter(Rating.text_id==text_id, Rating.created_by_id==current_user.id)
    if exist.count() != 0:

        if exist.first().rating != ratingType:
            db.session.delete(exist.first())
            db.session.commit()
        else:
            execute = False
            flash("You already {0} this word".format(action))

    if execute:

        rating = Rating(text_id=text_id, rating=ratingType, created_by_id=current_user.id)

        try:
            db.session.add(rating)
            db.session.commit()
            flash("{0} added to text".format(action))
        except:
            flash("Error")

app/templates/dictionary/_word.html
<li class="words">

    <h2><a href="{{ url_for('dictionary.word', term=word.word) }}">{{ word.word }}</a></h2>

    <h3>Definitions</h3>
    <ol class="definitions">

        {% for text in texts|rejectattr('type', "equalto", 2)|list %}

            <li>

                <div class="row">
                    <div class="col-md-1">
                        <ul class="rating">
                            <li><span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span></li>
                            <li>{{ text.ratings|sum(attribute='rating') }}</li>
                            <li><span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span></li>
                        </ul>
                    </div>

                    <div class="col-md-11">
                        <p>{{ text.text }}</p>

                        {% if text.sons != None %}
                            <ol class="examples">
                                {% for example in text.sons %}
                                    <li><i>{{ example.text }}</i></li>
                                {% endfor %}
                            </ol>
                        {% endif %}

                        <div class="more">
                            <span>by {{ text.lexicographer.username }}, {{ text.timestamp.strftime('%d-%m-%Y') }}</span>

                            <span><a href="{{ url_for("dictionary.language", language=text.language.name) }}">#{{ text.language.name }}</a></span>

                            {% for tag in text.tags %}
                                <span><a href="{{ url_for("dictionary.tag", tag=tag.tag) }}">#{{ tag.tag }}</a></span>
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </li>


        {% endfor %}
    </ol>

    {% if word.created_by_id == current_user.id %}
        <p><a href="{{ url_for('dictionary.delete_word', word=word.word) }}">Delete</a></p>
    {% endif %}
</li>

app/templates/dictionary/_words.html
{% if words != None %}
    <div class="words">
        <ul>
            {% for word in words %}
                <li>
                    <div class=" header-word">
                            <h2><a href="{{ url_for('word.word', term=word.word) }}">{{ word.word }}</a></h2>

                    </div>

                    <ol class="definitions">
                        <li>
                            <div class="row  row-word" style="border-right: 15px solid #{{ word.color }}">
                                <div class="col-md-1">
                                    <ul class="rating">
                                        <li><a href="{{ url_for("word.word", term=word.word, text_id=word.text_id, action="like") }}"><span class="glyphicon glyphicon-chevron-up" aria-hidden="true"></span></a></li>
                                        <li>{{ word.num_ratings }}</li>
                                        <li><a href="{{ url_for("word.word", term=word.word, text_id=word.text_id, action="like") }}"><span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span></a></li>
                                    </ul>
                                </div>

                                <div class="col-md-11">

                                    {{ word.text }}

                                    <div class="more">
                                        <span>by {{ word.username }},</span>
                                        <span >{{ word.timestamp.strftime('%d-%m-%Y') }}</span>
                                        <span>#{{ word.name }}</span>
                                        {% if word.created_by_id == current_user.id %}
                                            | <a href="{{ url_for('word.delete_word', word=word.word) }}">Delete</a>
                                        {% endif %}
                                        | <a href="{{ url_for('word.word', term=word.word) }}">More details</a>
                                    </div>
                                </div>
                            </div>

                        </li>
                    </ol>

                </li>
            {% endfor %}
        </ul>
    </div>
    {% if pagination is defined %}
        <nav aria-label="Page navigation" class="pagination-orientation">
            <ul class="pagination">

                {% if pagination.has_prev %}
                    <li class="previous"><a href="{{ url_for('dictionary.search', page=pagination.prev_num, term=term) }}">&larr; Previous</a></li>
                {% else %}
                    <li class="previous disabled"><a href="#">&larr; Previous</a></li>
                {% endif %}

                {% if pagination.has_next %}
                    <li class="next"><a href="{{ url_for('dictionary.search', page=pagination.next_num, term=term) }}">Next &rarr;</a></li>
                {% else %}
                    <li class="next disabled"><a href="#">Next &rarr;</a></li>
                {% endif %}

            </ul>
        </nav>
    {% endif %}

{% else %}
    No words found
{% endif %}

app/templates/dictionary/index.html
<!-- app/templates/home/index.html -->
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}
    | Home
{% endblock %}

{% block metatags %}

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="Description" CONTENT="A multilingual dictionary of slang and regionalisms! Get that slang that your immigrant friend are using, or just surprise your grandma with some new fancy words.">
    <meta name="robots" content="index,follow">

{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Dialleto</h1>
                    <hr class="intro-divider"><h3>A multilingual dictionary of slang and regionalisms!</h3>

                </div>
            </div>
        </div>
    </div>
</div>



<div class="container">
    <br/>
    {{ utils.flashed_messages() }}

    <div class="row">
        <div class="col-md-8">
            {% include '/dictionary/_words.html' %}
        </div>
        <div class="col-md-4 menu-right">
            <!-- Go to www.addthis.com/dashboard to customize your tools -->
            <div class="addthis_inline_follow_toolbox"></div>

            <h2>Languages</h2>
            <ol>
                {% for language in languages %}
                    <li style="border-right: 15px solid #{{ language.color }}"><a href="{{ url_for("dictionary.language", language=language.name) }}">#{{ language.name }}</a></li>
                {% endfor %}
            </ol>

            <h2>Categories</h2>
            <ol>
                {% for tag in tags %}
                    <li><a href="{{ url_for("dictionary.tag", tag=tag.tag) }}">#{{ tag.tag }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </div>

</div>
{% endblock %}

app/templates/dictionary/language.html
{% extends "base.html" %}

{% block title %}
    | Language: {{ language.name }}
{% endblock %}

{% block metatags %}

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="Description" CONTENT="A multilingual dictionary of slang and regionalisms! Get that slang that your immigrant friend are using, or just surprise your grandma with some new fancy words.">
    <meta name="robots" content="index,follow">

{% endblock %}

{% block body %}

    <div class="container">
        <h1>#{{ language.name }}</h1>
        {% include '/dictionary/_words.html' %}
    </div>

{% endblock %}

app/templates/dictionary/search.html
{% extends "base.html" %}

{% block title %}
    | Search
{% endblock %}

{% block metatags %}

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="Description" CONTENT="Find out what kids are saying these days, or maybe the hot immigrant you wanna hang out with.">
    <meta name="robots" content="index,follow">

{% endblock %}

{% block body %}

    <div class="container">
        <h1>Search Result</h1>
        {% include '/dictionary/_words.html' %}
    </div>

{% endblock %}

app/templates/dictionary/tag.html
{% extends "base.html" %}

{% block title %}
    | Tag: {{ tag }}
{% endblock %}

{% block metatags %}

    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="Description" CONTENT="A multilingual dictionary of slang and regionalisms! Get that slang that your immigrant friend are using, or just surprise your grandma with some new fancy words.">
    <meta name="robots" content="index,follow">

{% endblock %}

{% block body %}

    <div class="container">
        <h1>#{{ tag }}</h1>
        {% include '/dictionary/_words.html' %}
    </div>

{% endblock %}

app/templates/dictionary/word.html
<!-- app/templates/home/index.html -->
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}
    Home
{% endblock %}

{% block body %}


    <div class="container">
        <br>
        {{ utils.flashed_messages() }}
        <ul class="word">
            {% include '/dictionary/_word.html' %}
        </ul>
    </div>

{% endblock %}